### ISSUE TITLE
Support secondary storage

### ISSUE THREAD

**Issue by Napoleon0621** [bitleak/lmstfy#149]
### Search before asking

- [X] I had searched in the [issues](/https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Motivation

Secondary storage is important for data persistence.  Besides, with the growth of workloads, current pure redis mechanism is facing with a storage increases problem. Therefore there is a limitation for the amount of jobs to schedule. 

### Solution

By supporting secondary storage, jobs can be partially stored in places such as databases like mysql, spanner and etc.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Napoleon0621** [comment]
For DB schema:

create table LmstfyJob
(
    jobId     INT64(19) not null
        constraint PRIMARY_KEY
        primary key,
    namespace STRING(1024),
    queue     STRING(1024),
    body      BYTES(10485760),
    ttl       INT64(19) not null,
    delay     INT64(19) not null,
    tries     INT64(19) not null
);
@git-hulk any thoughts or comments, please?

**Comment by git-hulk** [comment]
For naming, we should use snake case instead of camel case:

table: LmstfyJob => lmstfy_jobs
fields: jobId => job_id

and `delay`/`ttl` should be `visible_at`/`expired_at` since it represents timestamp instead of delay seconds which we can't tell when it should be pumped into the memory tier. Also need the `created_at` to identify when the jobs was created.

**Comment by Napoleon0621** [comment]
ok, copy that.

**Comment by git-hulk** [comment]
Yes, sounds good to me
